<?php
declare(strict_types=1);

/**
 * Zentrale Inhaltsquelle für die Alltags-Abkürzungen im Kundenbereich.
 *
 * `goals` verwendet bewusst die bestehenden Zugangsschlüssel
 * zeit, energie, prompts und skills.
 *
 * @return array<int, array<string, mixed>>
 */
return [
    [
        'id' => 'nachrichten-diktieren',
        'number' => '01',
        'title' => 'Nachrichten sprechen statt tippen',
        'summary' => 'Sprich längere Nachrichten ein und prüfe anschließend nur noch den fertigen Text.',
        'categories' => ['sprechen'],
        'goals' => ['zeit', 'energie'],
        'format' => 'trick',
        'try_time' => '30–60 Sek.',
        'cost' => 'kostenlos',
        'device' => 'iPhone, iPad, Android oder Windows-PC',
        'setup' => 'praktisch keine',
        'benefit' => 'Weniger tippen',
        'problem' => 'Längere Nachrichten werden aufgeschoben, weil das Tippen zu viel Aufwand erzeugt.',
        'before' => 'Mehrere Minuten tippen und korrigieren.',
        'after' => '30–60 Sekunden sprechen, kurz prüfen, fertig.',
        'steps' => [
            'Cursor in ein Textfeld setzen.',
            'Spracheingabe öffnen.',
            'Nachricht normal sprechen.',
            'Text kurz kontrollieren.',
        ],
        'template' => 'Hallo Anna, danke für deine Nachricht. Ich schaffe es heute leider nicht mehr, schaue mir das aber morgen Vormittag an. Ich melde mich dann direkt bei dir.',
        'copy_label' => 'Beispiel kopieren',
        'tools' => [
            'iPhone/iPad: Mikrofon auf der Tastatur',
            'Android/Gboard: Mikrofon',
            'Windows: Windows + H',
        ],
        'saving' => 'geschätzt 1–3 Minuten bei längeren Nachrichten',
        'why' => 'Sprechen ersetzt viele einzelne Tastenanschläge; danach bleibt nur die kurze Kontrolle.',
        'warning' => 'Namen, Zahlen und Fremdwörter kontrollieren.',
        'featured' => false,
        'popular_rank' => 2,
        'skill_name' => null,
        'tags' => ['weniger tippen', 'Nachricht formulieren', 'diktieren'],
    ],
    [
        'id' => 'gedanken-zu-aufgaben',
        'number' => '02',
        'title' => 'Gedanken rein → Aufgaben raus',
        'summary' => 'Sprich ungeordnet los und lass daraus klare Aufgaben und nächste Schritte machen.',
        'categories' => ['sprechen', 'kopf'],
        'goals' => ['energie', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'ca. 2 Min.',
        'cost' => 'kostenlos möglich',
        'device' => 'Smartphone',
        'setup' => 'keine',
        'benefit' => 'Kopf entlasten',
        'problem' => 'Viele kleine Aufgaben und Gedanken sind gleichzeitig im Kopf, aber eine Liste daraus zu machen kostet zusätzliche Energie.',
        'before' => 'Unsortiertes Gedankenchaos.',
        'after' => 'Klare Aufgaben plus maximal drei nächste Schritte.',
        'steps' => [
            'Sprachmodus einer KI öffnen.',
            '60–90 Sekunden ungeordnet erzählen.',
            '„Fertig“ sagen.',
            'Aufgaben extrahieren lassen.',
        ],
        'template' => "Ich denke jetzt ungeordnet laut. Unterbrich mich nicht, bis ich ‚fertig‘ sage.\n\nDanach:\n1. extrahiere alle konkreten Aufgaben,\n2. fasse ähnliche Dinge zusammen,\n3. markiere Dinge unter fünf Minuten,\n4. nenne mir maximal drei sinnvolle nächste Schritte,\n5. erfinde keine Termine oder Prioritäten, die ich nicht genannt habe.",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['Sprachmodus einer KI, zum Beispiel ChatGPT Voice'],
        'saving' => 'geschätzt 5–15 Minuten',
        'why' => 'Die KI überführt ungeordnete Aussagen in eine sichtbare Liste und begrenzt die nächsten Schritte.',
        'warning' => 'Prioritäten bleiben eine menschliche Entscheidung.',
        'featured' => true,
        'popular_rank' => 1,
        'skill_name' => 'Mein Gedanken-Sortierer',
        'tags' => ['weniger tippen', 'schneller anfangen', 'etwas nicht vergessen', 'Aufgaben sortieren'],
    ],
    [
        'id' => 'rohgedanken-zu-nachricht',
        'number' => '03',
        'title' => 'Chaotische Gedanken → sendefertige Nachricht',
        'summary' => 'Gib den Inhalt roh vor und lass die KI nur die Formulierung übernehmen.',
        'categories' => ['ki-vorarbeit'],
        'goals' => ['zeit', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'direkt nutzbar',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Schneller antworten',
        'problem' => 'Der Inhalt einer Antwort ist klar, aber das Formulieren kostet unnötig Zeit.',
        'before' => 'Die gleiche Antwort mehrfach umformulieren.',
        'after' => 'Gedanken diktieren; die KI verbessert nur die Form.',
        'steps' => [
            'Die Nachricht einfügen, auf die du antwortest.',
            'Deine Rohantwort diktieren oder als Stichpunkte notieren.',
            'Beides in den Prompt einsetzen und eine Fassung erstellen lassen.',
            'Aussagen und Ton prüfen, bevor du die Nachricht sendest.',
        ],
        'template' => "Formuliere aus meiner Rohantwort eine Nachricht, die ich direkt senden könnte.\n\n– freundlich und natürlich\n– keine Floskeln\n– maximal 120 Wörter\n– meine Aussage nicht verändern\n– keine neuen Versprechen oder Termine hinzufügen\n– klingt wie ein normaler Mensch, nicht wie ein Geschäftsbrief\n\nNachricht, auf die ich antworte:\n[TEXT]\n\nMeine Rohantwort:\n[DIKTIEREN]",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['KI-Chat', 'Spracheingabe optional'],
        'saving' => 'geschätzt 2–5 Minuten pro Nachricht',
        'why' => 'Die Aussage bleibt deine; die KI übernimmt die sprachliche Ausarbeitung innerhalb klarer Grenzen.',
        'warning' => 'Aussagen und Ton kurz kontrollieren.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => 'Mein E-Mail-Helfer',
        'tags' => ['Nachricht formulieren', 'weniger tippen', 'Rohantwort', 'E-Mail'],
    ],
    [
        'id' => 'aufgabenberg-zu-woche',
        'number' => '04',
        'title' => 'Aufgabenberg → machbare Woche',
        'summary' => 'Ordne eine lange Aufgabenliste in eine Woche mit klaren Grenzen und freien Puffern.',
        'categories' => ['ki-vorarbeit'],
        'goals' => ['zeit', 'energie', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'direkt nutzbar',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Realistischer planen',
        'problem' => 'Eine lange Aufgabenliste zeigt nicht, was realistisch in eine Woche passt.',
        'before' => 'Eine lange Liste ohne sichtbare Wochenbegrenzung.',
        'after' => 'A-, B- und C-Aufgaben, höchstens drei Fokusblöcke pro Tag und sichtbar ausgelassene Aufgaben.',
        'steps' => [
            'Verfügbare Arbeitszeit eintragen.',
            'Alle Aufgaben als Liste ergänzen.',
            'Den Prompt ausführen und den vorgeschlagenen Wochenplan ansehen.',
            'Dauer und Energie selbst prüfen und den Plan bei Bedarf anpassen.',
        ],
        'template' => "Hilf mir, diese Woche realistisch zu planen.\n\nVerfügbare Arbeitszeit:\n[X Stunden]\n\nMeine Aufgaben:\n[LISTE]\n\nOrdne sie in:\nA – muss diese Woche passieren\nB – wäre sinnvoll\nC – kann warten\n\nErstelle anschließend maximal drei Fokusblöcke pro Tag.\n\nPlane nur 70 % meiner verfügbaren Zeit ein.\n\nZeige mir ausdrücklich, welche Aufgaben du nicht eingeplant hast.\n\nErfinde keine Deadlines.",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['KI-Chat'],
        'saving' => 'geschätzt 10–20 Minuten Planung',
        'why' => 'Die Einteilung und der freie Zeitpuffer machen sichtbar, was in die Woche passt und was warten kann.',
        'warning' => 'Energie und tatsächliche Dauer kennt die KI nicht zuverlässig.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => 'Mein Wochenplaner',
        'tags' => ['schneller anfangen', 'Wochenplanung', 'Aufgaben priorisieren'],
    ],
    [
        'id' => 'dokument-zu-handlung',
        'number' => '05',
        'title' => 'Langes Dokument → „Was muss ich tun?“',
        'summary' => 'Lass Fristen, Kosten und konkrete Handlungen aus einem langen Dokument herausarbeiten.',
        'categories' => ['ki-vorarbeit'],
        'goals' => ['zeit', 'energie', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'direkt nutzbar',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Dokumente schneller erfassen',
        'problem' => 'Lange Schreiben werden aufgeschoben, weil nicht klar ist, welche Informationen wirklich wichtig sind.',
        'before' => 'Ein langes Schreiben ohne klaren Handlungsüberblick.',
        'after' => 'Dokumentart, Handlung, Fristen, Kosten, Folgen und wichtige Originalstellen getrennt dargestellt.',
        'steps' => [
            'Prüfen, ob das Dokument in den verwendeten KI-Dienst eingegeben werden darf.',
            'Dokument hochladen oder den relevanten Text einfügen.',
            'Den Prompt ausführen und fehlende Angaben beachten.',
            'Wichtige Aussagen und die genannten Fundstellen im Original prüfen.',
        ],
        'template' => "Analysiere dieses Dokument ausschließlich anhand seines Inhalts.\n\nNenne mir:\n\n1. Was ist das überhaupt?\n2. Was muss ich konkret tun?\n3. Welche Fristen stehen darin?\n4. Welche Kosten, Beträge oder Verpflichtungen werden genannt?\n5. Was passiert, wenn ich nichts tue?\n6. Welche drei Stellen sollte ich selbst im Original lesen?\n\nTrenne ausdrücklich zwischen:\n– steht im Dokument\n– deine Interpretation\n\nWenn etwas fehlt, schreibe:\n‚nicht angegeben‘.",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['KI-Chat mit Text- oder Datei-Eingabe'],
        'saving' => 'geschätzt 10–30 Minuten bei längeren Dokumenten',
        'why' => 'Feste Fragen lenken den Blick auf Handlungsbedarf und kennzeichnen fehlende Informationen ausdrücklich.',
        'warning' => 'Verträge sowie medizinische, rechtliche oder finanzielle Unterlagen nicht ungeprüft übernehmen.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => 'Mein Dokumenten-Prüfer',
        'tags' => ['Dokument verstehen', 'Fristen finden', 'Kosten erkennen', 'Handlungsbedarf'],
    ],
    [
        'id' => 'angebote-vergleichen',
        'number' => '06',
        'title' => 'Angebote vergleichen, ohne selbst Tabellen zu bauen',
        'summary' => 'Vergleiche mehrere Optionen nach deinen Kriterien und mach fehlende Angaben sichtbar.',
        'categories' => ['ki-vorarbeit'],
        'goals' => ['zeit', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'direkt nutzbar',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Unterschiede schneller sehen',
        'problem' => 'Mehrere Angebote oder Produkte lassen sich schlecht vergleichen.',
        'before' => 'Informationen aus mehreren Optionen ohne einheitliche Struktur.',
        'after' => 'Eine kompakte Tabelle mit Unterschieden, Nachteilen und sichtbaren Wissenslücken.',
        'steps' => [
            'Die Optionen und alle vorhandenen Angaben sammeln.',
            'Die drei wichtigsten Entscheidungskriterien eintragen.',
            'Informationen und Prompt an die KI geben.',
            'Mit „?“ markierte Angaben vor der Entscheidung nachrecherchieren.',
        ],
        'template' => "Vergleiche diese Optionen für meine konkrete Entscheidung.\n\nMeine wichtigsten Kriterien:\n\n1. [KRITERIUM]\n2. [KRITERIUM]\n3. [KRITERIUM]\n\nErstelle eine kompakte Tabelle.\n\nVerwende ausschließlich Informationen, die ich geliefert habe.\n\nKennzeichne fehlende Angaben mit ‚?‘ statt sie zu schätzen.\n\nNenne danach:\n\n– den wichtigsten Unterschied,\n– den größten möglichen Nachteil jeder Option,\n– welche eine fehlende Information meine Entscheidung am stärksten verändern könnte.",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['KI-Chat'],
        'saving' => null,
        'why' => 'Einheitliche Kriterien und sichtbare Lücken machen die Optionen direkt vergleichbar.',
        'warning' => 'Fehlende Informationen dürfen nicht erfunden werden.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => 'Mein Vergleichsassistent',
        'tags' => ['etwas vergleichen', 'Angebote', 'Produkte', 'Entscheidung vorbereiten'],
    ],
    [
        'id' => 'gespraech-durchspielen',
        'number' => '07',
        'title' => 'Schwieriges Gespräch vorher durchspielen',
        'summary' => 'Übe ein Gespräch Schritt für Schritt und erhalte anschließend knappes Feedback.',
        'categories' => ['ki-vorarbeit'],
        'goals' => ['energie', 'prompts'],
        'format' => 'prompt-rezept',
        'try_time' => 'ca. 5 Min.',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Klarer ins Gespräch gehen',
        'problem' => 'Ein schwieriges Gespräch läuft vorab ständig im Kopf.',
        'before' => 'Gedankliche Vorbereitungsschleifen ohne Probe.',
        'after' => 'Ein kurzes Rollenspiel mit Feedback zu Klarheit und einer verbesserten Formulierung.',
        'steps' => [
            'Rolle der anderen Person und eigenes Gesprächsziel eintragen.',
            'Den Prompt starten und auf jede Reaktion einzeln antworten.',
            'Das Rollenspiel ungefähr fünf Minuten durchführen.',
            'Das abschließende Feedback prüfen und eine Formulierung verbessern.',
        ],
        'template' => "Wir simulieren ein Gespräch.\n\nDu spielst:\n[Chef / Kunde / Kollege / andere Person]\n\nMein Ziel:\n[ZIEL]\n\nReagiere realistisch, aber nicht künstlich aggressiv.\n\nStelle immer nur eine Frage oder Reaktion gleichzeitig und warte auf meine Antwort.\n\nNach ungefähr fünf Minuten beenden wir das Rollenspiel.\n\nDanach sagst du mir nur:\n\n– was ich klar formuliert habe,\n– wo meine Aussage missverständlich war,\n– welche eine Formulierung ich verbessern könnte.",
        'copy_label' => 'Prompt kopieren',
        'tools' => ['KI-Chat oder KI-Sprachmodus'],
        'saving' => null,
        'why' => 'Das Rollenspiel macht Aussagen hör- und prüfbar, bevor das echte Gespräch beginnt.',
        'warning' => 'Eine KI kann die echte Reaktion eines Menschen nicht vorhersagen.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => 'Meine Gesprächsvorbereitung',
        'tags' => ['Gespräch vorbereiten', 'Rollenspiel', 'Formulierung üben'],
    ],
    [
        'id' => 'ki-einmal-einstellen',
        'number' => '08',
        'title' => 'KI einmal einstellen statt immer wieder neu erklären',
        'summary' => 'Speichere wiederkehrende Regeln einmal und erhalte konsistentere Antworten.',
        'categories' => ['einrichten'],
        'goals' => ['skills', 'zeit'],
        'format' => 'skill-ablauf',
        'try_time' => 'ca. 3 Min.',
        'cost' => 'abhängig vom verwendeten KI-Dienst',
        'device' => 'Smartphone oder Computer',
        'setup' => 'ungefähr 3 Minuten',
        'benefit' => 'Weniger Regeln wiederholen',
        'problem' => 'Bei jedem KI-Chat werden dieselben Regeln erneut erklärt.',
        'before' => 'Wiederkehrende Vorgaben in jedem Chat neu eingeben.',
        'after' => 'Ein gespeicherter Helfer berücksichtigt die festen Regeln bei jeder passenden Aufgabe.',
        'steps' => [
            'Ein neues KI-Projekt oder einen gespeicherten Assistenten anlegen.',
            'Die festen Regeln als Anweisung einfügen.',
            'Den Helfer verständlich benennen und speichern.',
            'Mit einer typischen Alltagsaufgabe testen und bei Bedarf anpassen.',
        ],
        'template' => "Hilf mir bei Alltagsorganisation.\n\n– Antworte kurz und konkret.\n– Gib maximal drei nächste Schritte gleichzeitig.\n– Zerlege Aufgaben so weit, dass der erste Schritt sofort ausführbar ist.\n– Erfinde keine Termine, Prioritäten oder Fakten.\n– Wenn ich viele Aufgaben nenne, zeige mir zuerst, was wahrscheinlich warten kann.\n– Beende Antworten mit genau einem konkreten nächsten Schritt.",
        'copy_label' => 'Anweisung kopieren',
        'tools' => ['KI-Projekt oder gespeicherter Assistent'],
        'saving' => null,
        'why' => 'Gespeicherte Regeln müssen bei wiederkehrenden Aufgaben nicht jedes Mal neu eingegeben werden.',
        'warning' => 'Wichtige Fakten und vorgeschlagene Prioritäten weiterhin selbst prüfen.',
        'featured' => false,
        'popular_rank' => 5,
        'skill_name' => 'Mein Alltags-Helfer',
        'tags' => ['etwas wiederverwenden', 'eigener Skill', 'Alltagsorganisation'],
    ],
    [
        'id' => 'textersetzungen',
        'number' => '09',
        'title' => 'Drei Zeichen → ganzer Standardsatz',
        'summary' => 'Ersetze kurze Kürzel automatisch durch Adressen, Links oder ganze Standardantworten.',
        'categories' => ['einrichten', 'geraete'],
        'goals' => ['zeit', 'skills'],
        'format' => 'trick',
        'try_time' => 'ca. 30 Sek. je Textbaustein',
        'cost' => 'kostenlos',
        'device' => 'Smartphone oder Computer',
        'setup' => 'etwa 30 Sekunden pro Textbaustein',
        'benefit' => 'Standardsätze sofort einsetzen',
        'problem' => 'Adressen, Standardantworten oder Links werden ständig neu getippt.',
        'before' => 'Häufige Angaben und Antworten immer wieder vollständig tippen.',
        'after' => 'Ein kurzes Kürzel wird automatisch zum vollständigen Textbaustein.',
        'steps' => [
            'Die Einstellungen für Textersetzungen auf dem Gerät öffnen.',
            'Ein seltenes Kürzel mit zwei Sonderzeichen festlegen.',
            'Den vollständigen Textbaustein hinterlegen.',
            'Die Ersetzung in einem Textfeld testen.',
        ],
        'template' => ";;adr → [EIGENE ADRESSE]\n;;mail → [EIGENE E-MAIL-ADRESSE]\n;;danke → Vielen Dank für Ihre Nachricht. Ich schaue mir das an und melde mich so bald wie möglich zurück.",
        'copy_label' => 'Beispiele kopieren',
        'tools' => ['Textersetzung des verwendeten Geräts'],
        'saving' => null,
        'why' => 'Das Gerät ersetzt ein kurzes, eindeutiges Kürzel automatisch durch den gespeicherten Text.',
        'warning' => 'Zwei Sonderzeichen wie „;;“ verwenden, damit normale Wörter nicht versehentlich ersetzt werden.',
        'featured' => false,
        'popular_rank' => 3,
        'skill_name' => null,
        'tags' => ['weniger tippen', 'etwas wiederverwenden', 'Standardtext', 'Textersetzung'],
    ],
    [
        'id' => 'zwischenablageverlauf',
        'number' => '10',
        'title' => 'Häufige Texte mit Windows + V wiederfinden',
        'summary' => 'Öffne den Zwischenablageverlauf und hefte oft gebrauchte Einträge dort an.',
        'categories' => ['geraete'],
        'goals' => ['zeit', 'energie'],
        'format' => 'trick',
        'try_time' => 'sofort',
        'cost' => 'in Windows enthalten',
        'device' => 'Windows-PC',
        'setup' => 'beim ersten Mal gegebenenfalls aktivieren',
        'benefit' => 'Weniger nach Texten suchen',
        'problem' => 'Links, Texte und Standardabsätze werden immer wieder gesucht.',
        'before' => 'Häufig verwendete Inhalte jedes Mal neu suchen oder kopieren.',
        'after' => 'Zuletzt kopierte und angeheftete Inhalte über Windows + V direkt auswählen.',
        'steps' => [
            'Windows + V drücken.',
            'Den Zwischenablageverlauf beim ersten Öffnen gegebenenfalls aktivieren.',
            'Links oder Texte wie gewohnt kopieren.',
            'Wichtige Einträge im Verlauf anheften.',
        ],
        'template' => 'Windows + V',
        'copy_label' => 'Tastenkürzel kopieren',
        'tools' => ['Windows-Zwischenablageverlauf'],
        'saving' => null,
        'why' => 'Der Verlauf hält kopierte Inhalte an einem Ort bereit; angeheftete Einträge bleiben schnell erreichbar.',
        'warning' => 'Keine Passwörter oder vertraulichen Daten anheften.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => null,
        'tags' => ['weniger suchen', 'etwas wiederverwenden', 'Windows', 'Zwischenablage'],
    ],
    [
        'id' => 'screenshot-text-kopieren',
        'number' => '11',
        'title' => 'Text aus Screenshots kopieren',
        'summary' => 'Hole Telefonnummern, Fehlermeldungen oder Textpassagen direkt aus einem Bild.',
        'categories' => ['geraete'],
        'goals' => ['zeit', 'energie'],
        'format' => 'trick',
        'try_time' => 'sofort',
        'cost' => 'in Windows enthalten',
        'device' => 'Windows-PC',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Bildtext direkt übernehmen',
        'problem' => 'Text befindet sich in einem Bild oder einer Anwendung und lässt sich nicht markieren.',
        'before' => 'Text aus einem Bild von Hand abtippen.',
        'after' => 'Erkannten Text direkt markieren und kopieren.',
        'steps' => [
            'Windows + Shift + S drücken.',
            'Den gewünschten Bereich auswählen.',
            'Den Screenshot im Snipping Tool öffnen.',
            '„Textaktionen“ verwenden und den Text kopieren.',
        ],
        'template' => 'Windows + Shift + S',
        'copy_label' => 'Tastenkürzel kopieren',
        'tools' => ['Windows Snipping Tool: Textaktionen'],
        'saving' => null,
        'why' => 'Die Textaktionen erkennen Schrift im Screenshot und machen sie kopierbar.',
        'warning' => 'Zahlen kurz überprüfen.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => null,
        'tags' => ['weniger tippen', 'Screenshot', 'Text erkennen', 'Windows'],
    ],
    [
        'id' => 'papier-zu-pdf',
        'number' => '12',
        'title' => 'Papier → durchsuchbares PDF',
        'summary' => 'Scanne Briefe als ordentlich benannte PDFs statt sie nur zu fotografieren.',
        'categories' => ['geraete'],
        'goals' => ['energie'],
        'format' => 'trick',
        'try_time' => 'direkt nutzbar',
        'cost' => 'kostenlos möglich',
        'device' => 'iPhone oder Android-Smartphone',
        'setup' => 'keine besondere Einrichtung',
        'benefit' => 'Dokumente leichter wiederfinden',
        'problem' => 'Briefe werden nur fotografiert und später nicht mehr gefunden.',
        'before' => 'Einzelne Fotos ohne einheitlichen Namen.',
        'after' => 'Ein ordentliches, benanntes PDF mit allen Seiten.',
        'steps' => [
            'Den Dokumenten-Scanner auf dem Smartphone öffnen.',
            'Alle Seiten nacheinander scannen.',
            'Ausschnitt und Lesbarkeit prüfen und als PDF sichern.',
            'Die Datei nach Datum, Absender und Thema benennen.',
        ],
        'template' => '2026-09-05_Absender_Thema.pdf',
        'copy_label' => 'Benennung kopieren',
        'tools' => [
            'iPhone: Notizen → Dokumente scannen',
            'Google Drive: Scan-Funktion',
        ],
        'saving' => null,
        'why' => 'Ein Dokumentenscan bündelt mehrere Seiten in einer Datei; ein klarer Name erleichtert das spätere Wiederfinden.',
        'warning' => 'Bei sensiblen Dokumenten auf die verwendete Cloud-Speicherung achten.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => null,
        'tags' => ['weniger suchen', 'Dokument scannen', 'PDF', 'Papier digitalisieren'],
    ],
    [
        'id' => 'lange-texte-anhoeren',
        'number' => '13',
        'title' => 'Lange Texte einfach anhören',
        'summary' => 'Lass dir Artikel oder Anleitungen vorlesen, wenn Zuhören gerade leichter ist als Lesen.',
        'categories' => ['geraete'],
        'goals' => ['energie'],
        'format' => 'tipp',
        'try_time' => 'direkt nutzbar',
        'cost' => 'im Gerät beziehungsweise Browser enthalten',
        'device' => 'Windows-PC, iPhone oder Android',
        'setup' => 'je nach Gerät keine oder einmalige Aktivierung',
        'benefit' => 'Lesestapel leichter anfangen',
        'problem' => 'Ein langer Artikel oder eine Anleitung wird immer wieder auf später verschoben.',
        'before' => 'Ein langer Text bleibt ungelesen.',
        'after' => 'Der Text lässt sich beim Gehen, Aufräumen oder bei anderen einfachen Tätigkeiten anhören.',
        'steps' => [
            'Den Artikel oder die Anleitung öffnen.',
            'Die Vorlesefunktion des Geräts oder Browsers starten.',
            'Bei Tabellen, Formeln oder komplexem Layout wieder selbst ins Original schauen.',
        ],
        'template' => null,
        'copy_label' => null,
        'tools' => [
            'Microsoft Edge: Laut vorlesen',
            'iPhone: Bedienungshilfen → Lesen & Sprechen',
            'Android: Vorlesen / Select to Speak',
        ],
        'saving' => null,
        'why' => 'Die Vorlesefunktion macht aus einer Leseaufgabe eine Hörmöglichkeit.',
        'warning' => 'Tabellen, Formeln und komplexe Layouts eignen sich weniger.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => null,
        'tags' => ['schneller anfangen', 'Text anhören', 'Vorlesen', 'Bedienungshilfe'],
    ],
    [
        'id' => 'gedanke-als-erinnerung',
        'number' => '14',
        'title' => 'Gedanken sofort als Erinnerung speichern',
        'summary' => 'Sprich eine Erinnerung aus, bevor der Gedanke wieder verschwunden ist.',
        'categories' => ['kopf'],
        'goals' => ['energie'],
        'format' => 'trick',
        'try_time' => 'wenige Sekunden',
        'cost' => 'abhängig vom Gerät beziehungsweise Dienst',
        'device' => 'iPhone oder Android-Smartphone',
        'setup' => 'Sprachassistent und Erinnerungs-App müssen eingerichtet sein',
        'benefit' => 'Weniger im Kopf behalten',
        'problem' => 'Ein Gedanke taucht auf und ist wenige Stunden später vergessen.',
        'before' => 'Eine Aufgabe bleibt nur als flüchtiger Gedanke im Kopf.',
        'after' => 'Eine Erinnerung mit Aufgabe und passendem Zeitpunkt oder Ort ist gespeichert.',
        'steps' => [
            'Den Sprachassistenten des Smartphones öffnen.',
            'Aufgabe und gewünschten Zeitpunkt oder Ort aussprechen.',
            'Die erkannte Erinnerung anzeigen lassen.',
            'Uhrzeit und Aufgabe kurz prüfen und gegebenenfalls korrigieren.',
        ],
        'template' => "Erinnere mich heute um 17 Uhr daran, Peter zurückzurufen.\n\nOder:\n\nErinnere mich daran, den Brief mitzunehmen, wenn ich das Haus verlasse.",
        'copy_label' => 'Beispiele kopieren',
        'tools' => [
            'Siri und Apple Erinnerungen',
            'Android/Gemini und Google Tasks beziehungsweise passende Erinnerungsfunktion',
        ],
        'saving' => null,
        'why' => 'Der Sprachbefehl hält den Gedanken direkt als abrufbare Erinnerung fest.',
        'warning' => 'Erkannte Uhrzeit und Aufgabe kurz überprüfen.',
        'featured' => false,
        'popular_rank' => 4,
        'skill_name' => null,
        'tags' => ['etwas nicht vergessen', 'Erinnerung', 'Sprachassistent', 'Aufgabe erfassen'],
    ],
    [
        'id' => '20-sekunden-parknotiz',
        'number' => '15',
        'title' => 'Die 20-Sekunden-Parknotiz',
        'summary' => 'Halte vor einer Unterbrechung fest, wo du stehst und was als Nächstes kommt.',
        'categories' => ['kopf'],
        'goals' => ['zeit', 'energie'],
        'format' => 'tipp',
        'try_time' => '20 Sek.',
        'cost' => 'ohne zusätzliche Kosten möglich',
        'device' => 'Smartphone, Computer oder Papier',
        'setup' => 'keine',
        'benefit' => 'Schneller wieder einsteigen',
        'problem' => 'Nach einer Unterbrechung kostet es unnötig Zeit, wieder herauszufinden, wo man bei einer Aufgabe war.',
        'before' => 'Nach der Pause erst wieder rekonstruieren, wo die Arbeit stehen geblieben ist.',
        'after' => 'Stand, nächster Schritt und eine offene Frage warten als kurze Parknotiz.',
        'steps' => [
            'Vor einer Unterbrechung kurz den aktuellen Stand notieren.',
            'Die nächste konkrete Handlung festhalten.',
            'Eine mögliche offene oder blockierende Frage ergänzen.',
            'Die Notiz dort speichern, wo du die Aufgabe wieder aufnimmst.',
        ],
        'template' => "Stand:\nWo bin ich gerade?\n\nNächster Schritt:\nWelche ganz konkrete Handlung kommt als Nächstes?\n\nOffen:\nWelche Frage blockiert mich eventuell?",
        'copy_label' => 'Vorlage kopieren',
        'tools' => ['Notiz-App, Aufgaben-App oder Papier'],
        'saving' => 'geschätzt 2–10 Minuten beim Wiedereinstieg',
        'why' => 'Die Notiz bewahrt den aktuellen Arbeitskontext für den späteren Wiedereinstieg.',
        'warning' => 'Den nächsten Schritt so konkret formulieren, dass er ohne erneutes Sortieren verständlich bleibt.',
        'featured' => false,
        'popular_rank' => null,
        'skill_name' => null,
        'tags' => ['schneller anfangen', 'Wiedereinstieg', 'Kopf entlasten', 'Vorlage'],
    ],
];
